name: Build-Package-UserService

on:
  push:
    paths:
      - 'src/userservice/**'
      - '.github/workflows/build-userservice.yml'

env:
  DOCKER_RGISTRY: docker.pkg.github.com/cshep4/premier-predictor-microservices
  GONOSUMDB: github.com/cshep4
  GOPRIVATE: github.com/cshep4

jobs:
  build-and-publish-latest:
    name: Build and Push UserService
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        run: |
          docker login docker.pkg.github.com -u cshep4 -p ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'

      - name: Install Dependencies
        run: |
          GO111MODULE=on go get github.com/golang/mock/mockgen@v1.4.4

      - name: Granting Private Modules Access
        run: |
          git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/cshep4".insteadOf "https://github.com/cshep4"

      - name: Build
        working-directory: src/userservice
        run: |
          go generate ./...
          go mod vendor
          docker build \
            -t ${{ env.DOCKER_RGISTRY }}/userservice:latest \
            -t ${{ env.DOCKER_RGISTRY }}/userservice:$(echo ${GITHUB_SHA} | cut -c1-8) \
            -t ${{ env.DOCKER_RGISTRY }}/userservice:${GITHUB_REF##*/}_$(echo ${GITHUB_SHA} | cut -c1-8) \
            .

      - name: Push
        run: |
          docker push ${{ env.DOCKER_RGISTRY }}/userservice
