name: Build-Package

on: push

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        run: |
          docker login docker.pkg.github.com -u cshep4 -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build leagueservice
        run: |
          docker build --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -t docker.pkg.github.com/cshep4/premier-predictor-microservices/leagueservice:latest src/leagueservice
          docker push docker.pkg.github.com/cshep4/premier-predictor-microservices/leagueservice:latest
          docker tag docker.pkg.github.com/cshep4/premier-predictor-microservices/leagueservice:latest docker.pkg.github.com/cshep4/premier-predictor-microservices/leagueservice:$(echo ${GITHUB_SHA} | cut -c1-8)
          docker push docker.pkg.github.com/cshep4/premier-predictor-microservices/leagueservice:$(echo ${GITHUB_SHA} | cut -c1-8)

      - name: Build kauthservice
        run: |
          docker build -f src/kauthservice/src/main/docker/Dockerfile.multistage -t docker.pkg.github.com/cshep4/premier-predictor-microservices/kauthservice:latest src/kauthservice
          docker push docker.pkg.github.com/cshep4/premier-predictor-microservices/kauthservice:latest
          docker tag docker.pkg.github.com/cshep4/premier-predictor-microservices/kauthservice:latest docker.pkg.github.com/cshep4/premier-predictor-microservices/kauthservice:$(echo ${GITHUB_SHA} | cut -c1-8)
          docker push docker.pkg.github.com/cshep4/premier-predictor-microservices/kauthservice:$(echo ${GITHUB_SHA} | cut -c1-8)

      - name: Build gatewayservice
        run: |
          cp -R proto-gen/model/proto src/gatewayservice/proto
          docker build -t docker.pkg.github.com/cshep4/premier-predictor-microservices/gatewayservice:latest src/gatewayservice
          docker push docker.pkg.github.com/cshep4/premier-predictor-microservices/gatewayservice:latest
          docker tag docker.pkg.github.com/cshep4/premier-predictor-microservices/gatewayservice:latest docker.pkg.github.com/cshep4/premier-predictor-microservices/gatewayservice:$(echo ${GITHUB_SHA} | cut -c1-8)
          docker push docker.pkg.github.com/cshep4/premier-predictor-microservices/gatewayservice:$(echo ${GITHUB_SHA} | cut -c1-8)

      - name: Build fixtureservice
        run: |
          cp -R proto-gen/model/proto src/fixtureservice/proto
          docker build -t docker.pkg.github.com/cshep4/premier-predictor-microservices/fixtureservice:latest src/fixtureservice
          docker push docker.pkg.github.com/cshep4/premier-predictor-microservices/fixtureservice:latest
          docker tag docker.pkg.github.com/cshep4/premier-predictor-microservices/fixtureservice:latest docker.pkg.github.com/cshep4/premier-predictor-microservices/fixtureservice:$(echo ${GITHUB_SHA} | cut -c1-8)
          docker push docker.pkg.github.com/cshep4/premier-predictor-microservices/fixtureservice:$(echo ${GITHUB_SHA} | cut -c1-8)
