name: Build-Package

on: push

env:
  DOCKER_RGISTRY: docker.pkg.github.com/cshep4/premier-predictor-microservices
  GONOSUMDB: github.com/cshep4
  GOPRIVATE: github.com/cshep4

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        run: |
          docker login docker.pkg.github.com -u cshep4 -p ${{ secrets.GITHUB_TOKEN }}

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/cshep4".insteadOf "https://github.com/cshep4"

      - name: Build leagueservice
        run: |
          cd src/leagueservice
          GO111MODULE=on go get github.com/golang/mock/mockgen@v1.4.4
          go mod tidy
          go generate ./...
          go mod vendor
          cd ..
          docker build --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -t ${{ env.DOCKER_RGISTRY }}/leagueservice:latest -t ${{ env.DOCKER_RGISTRY }}/leagueservice:$(echo ${GITHUB_SHA} | cut -c1-8) src/leagueservice
          docker push ${{ env.DOCKER_RGISTRY }}/leagueservice

      - name: Build kauthservice
        run: |
          docker build --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -f src/kauthservice/src/main/docker/Dockerfile.multistage -t ${{ env.DOCKER_RGISTRY }}/kauthservice:latest -t ${{ env.DOCKER_RGISTRY }}/kauthservice:$(echo ${GITHUB_SHA} | cut -c1-8) src/kauthservice
          docker push ${{ env.DOCKER_RGISTRY }}/kauthservice

      - name: Build gatewayservice
        run: |
          cp -R proto-gen/model/proto src/gatewayservice/proto
          docker build --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -t ${{ env.DOCKER_RGISTRY }}/gatewayservice:latest -t ${{ env.DOCKER_RGISTRY }}/gatewayservice:$(echo ${GITHUB_SHA} | cut -c1-8) src/gatewayservice
          docker push ${{ env.DOCKER_RGISTRY }}/gatewayservice

      - name: Build fixtureservice
        run: |
          cp -R proto-gen/model/proto src/fixtureservice/proto
          docker build --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -t ${{ env.DOCKER_RGISTRY }}/fixtureservice:latest -t ${{ env.DOCKER_RGISTRY }}/fixtureservice:$(echo ${GITHUB_SHA} | cut -c1-8) src/fixtureservice
          docker push ${{ env.DOCKER_RGISTRY }}/fixtureservice
