name: Build-Package

on: push

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean protos
        run: |
          cp -R proto-gen/model/proto src/gatewayservice/proto
          cp -R proto-gen/model/proto src/fixtureservice/proto

      - name: Build and Publish gatewayservice
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: gatewayservice # Provide only Docker image name
          extract-git-tag: true # Provide flag to extract Docker image tag from git reference
          build-context: ./src/gatewayservice # Provide path to the folder with the Dockerfile
