# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Set up secrets in your workspace: GKE_PROJECT with the name of the project and GKE_SA_KEY with the Base64 encoded JSON service account key (https://github.com/GoogleCloudPlatform/github-actions/tree/docs/service-account-key/setup-gcloud#inputs).
#
# 3. Change the values for the GKE_ZONE, GKE_CLUSTER, IMAGE, and DEPLOYMENT_NAME environment variables (below).
#
# For more support on how to run the workflow, please visit https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/gke
#
# GKE_SA_KEY = cat <file>.json | base64

name: Cleanup-GKE-TLS

on: workflow_dispatch

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: premier-predictor
  GKE_ZONE: europe-west2-a

jobs:
  deploy:
    name: Configure TLS
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Gcloud authenticate docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Helm tool installer
        uses: Azure/setup-helm@v1
        id: install

      - name: Clean up previous configuration
        run: |-
          kubectl delete -f https://www.getambassador.io/yaml/aes-crds.yaml &&
          kubectl delete -f https://www.getambassador.io/yaml/aes.yaml &&
          kubectl delete -f https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.crds.yaml
          kubectl delete -f ./ambassador/https.yaml
          kubectl delete -f ./ambassador/cert.yaml
          kubectl delete -f ./ambassador/acme.yaml
          helm uninstall cert-manager -n cert-manager

      - name: Install Ambassador Edge Stack
        run: |-
          kubectl apply -f https://www.getambassador.io/yaml/aes-crds.yaml && \
          kubectl wait --for condition=established --timeout=90s crd -lproduct=aes && \
          kubectl apply -f https://www.getambassador.io/yaml/aes.yaml && \
          kubectl -n ambassador wait --for condition=available --timeout=90s deploy -lproduct=aes

      - name: Configure TLS
        run: |-
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.crds.yaml
          helm repo add jetstack https://charts.jetstack.io && helm repo update
          kubectl apply -f ./ambassador/ns.yaml
          kubectl apply -f ./ambassador/https.yaml
          kubectl apply -f ./ambassador/cert.yaml
          helm install \
            cert-manager jetstack/cert-manager \
            --namespace cert-manager
          kubectl -n cert-manager rollout status deploy/cert-manager-webhook
          sleep 120
          kubectl apply -f ./ambassador/acme.yaml
